# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8180/order
Content-Type: application/json

[
  {
    "name": "Produto 1",
    "code": "az9888",
    "price": 9,
    "quantity": 5
  },
  {
    "name": "Produto 2",
    "code": "bz9890",
    "price": 5.98,
    "quantity": 2
  }
]

###

GET http://localhost:8180/order-repository

###